[package]
name = "ic_websocket_example_timer_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.9.2"
ic-cdk-macros = "0.7.0"
ic-cdk-timers = "0.4.0"
serde = "1.0.176"
serde_cbor = "0.11.2"
ic-websocket-cdk = { git = "https://github.com/omnia-network/ic-websocket-cdk-rs", rev = "d27c2f25b3f0da044b80628dd843fee76fb356c4" }
