[package]
name = "ic_websocket_example_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.3"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
ic-websocket-cdk = { git = "https://github.com/omnia-network/ic-websocket-cdk-rs.git", rev = "10550522b42e5fa103e5ebd502d8fdae139c4c54" }
serde = "1.0.176"
